# Generated by Django 5.2 on 2025-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(default='Happy', max_length=20),
        ),
    ]
